version: "3"
services:
  padilhadev_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: padilhadev_web
    environment:
      VIRTUAL_HOST: padilha.dev
      LETSENCRYPT_HOST: padilha.dev
      LETSENCRYPT_EMAIL: padilhaght+letsencrypt@gmail.com
    expose:
      - 80
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "10"

networks:
  default:
    name: nginx-proxy
    external: true